'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Download, FileText, LoaderCircle, Play, Plus, Upload, X, ZoomIn, ZoomOut } from 'lucide-react';
import { fileKind, fileUrl, type Project, type FileEntry } from '@/lib/types';
import { api } from './workspace';
const sizeOf = (n: number) => n < 1024 ** 2 ? `${(n / 1024).toFixed(0)} KB` : `${(n / 1024 ** 2).toFixed(1)} MB`;
export function MediaViewer({ project, files, current, onChange, onClose }: { project: Project; files: FileEntry[]; current: string; onChange: (p: string) => void; onClose: () => void }) {
  const [zoom, setZoom] = useState(1); const closeRef = useRef<HTMLButtonElement>(null);
  const index = files.findIndex(f => f.path === current);
  const move = useCallback((direction: number) => { if (files.length) { onChange(files[(index + direction + files.length) % files.length].path); setZoom(1); } }, [files, index, onChange]);
  useEffect(() => { const previous = document.activeElement as HTMLElement; closeRef.current?.focus(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old; previous?.focus(); }; }, []);
  useEffect(() => { const handle = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); if (e.key === 'ArrowRight') move(1); if (e.key === 'ArrowLeft') move(-1); }; window.addEventListener('keydown', handle); return () => window.removeEventListener('keydown', handle); }, [move, onClose]);
  useEffect(() => { document.querySelector('.filmstrip .selected')?.scrollIntoView({ block: 'nearest', inline: 'center', behavior: 'smooth' }); }, [current]);
  return <div className="lightbox" role="dialog" aria-modal="true" aria-label="Media viewer" onKeyDown={trapFocus}><header><div><span className="eyebrow">{project.name} / MEDIA LIBRARY</span><strong>{current.split('/').pop()}</strong></div><div><span>{index + 1} / {files.length}</span><button className="icon-button" aria-label="Zoom out" onClick={() => setZoom(Math.max(0.5, zoom - 0.25))}><ZoomOut size={19}/></button><button className="zoom-value" onClick={() => setZoom(1)}>{Math.round(zoom * 100)}%</button><button className="icon-button" aria-label="Zoom in" onClick={() => setZoom(Math.min(4, zoom + 0.25))}><ZoomIn size={19}/></button><a className="icon-button" aria-label="Download image" href={`${fileUrl(project.id, current)}&download=1`}><Download size={19}/></a><button ref={closeRef} className="icon-button" aria-label="Close viewer" onClick={onClose}><X size={22}/></button></div></header><div className="lightbox-stage"><button className="lightbox-prev" aria-label="Previous image" onClick={() => move(-1)}><ChevronLeft size={27}/></button><div className={`lightbox-image ${zoom > 1 ? 'zoomed' : ''}`}>{fileKind(current) === 'image' ? <img key={current} src={fileUrl(project.id, current)} alt={current} style={zoom > 1 ? { width: `${zoom * 75}%`, maxWidth: 'none', maxHeight: 'none' } : { maxWidth: `${zoom * 90}%`, maxHeight: `${zoom * 100}%` }}/> : fileKind(current) === 'video' ? <video key={current} controls autoPlay src={fileUrl(project.id, current)}/> : <audio key={current} controls src={fileUrl(project.id, current)}/>}</div><button className="lightbox-next" aria-label="Next image" onClick={() => move(1)}><ChevronRight size={27}/></button></div><div className="filmstrip">{files.map((f, i) => <button key={f.path} className={f.path === current ? 'selected' : ''} aria-label={`Media ${i + 1}: ${f.path}`} onClick={() => { onChange(f.path); setZoom(1); }}>{f.kind === 'image' ? <img loading="lazy" src={fileUrl(project.id, f.path)} alt=""/> : <Play size={20}/>}</button>)}</div><footer><span>← → Browse</span><span>{current}</span><span>Esc Close</span></footer></div>;
}
function trapFocus(e: React.KeyboardEvent<HTMLDivElement>) {
  if (e.key !== 'Tab') return;
  const elements = e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input, select, textarea');
  const first = elements[0], last = elements[elements.length - 1];
  if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); }
  if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); }
}
export function UploadDialog({ project, note, onClose, onDone }: { project: Project; note: boolean; onClose: () => void; onDone: (p?: string) => Promise<void> }) {
  const [folder, setFolder] = useState(''); const [files, setFiles] = useState<File[]>([]); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [progress, setProgress] = useState(''); const [drag, setDrag] = useState(false);
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement; closeRef.current?.focus(); return () => previous?.focus(); }, []);
  async function submit() {
    setBusy(true); setError('');
    try {
      let created = '';
      if (note) { created = `${folder ? folder.replace(/\/$/, '') + '/' : ''}${name.endsWith('.md') ? name : name + '.md'}`; await api('/api/file', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: project.id, path: created, content: `# ${name.replace(/\.md$/, '')}\n\n`, create: true }) }); }
      else { for (let i = 0; i < files.length; i++) { const file = files[i]; setProgress(`${i + 1} / ${files.length} · ${file.name}`); if (file.size > 4 * 1024 * 1024) throw new Error(`${file.name}: maximum 4 MB per file`); const form = new FormData(); form.set('project', project.id); form.set('path', `${folder ? folder.replace(/\/$/, '') + '/' : ''}${file.name}`); form.set('file', file); await api('/api/file', { method: 'POST', body: form }); setFiles(prev => prev.filter(f => f !== file)); } }
      await onDone(created); onClose();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); setProgress(''); }
  }
  return <div className="modal-backdrop" onClick={() => !busy && onClose()}><div className="upload-dialog" role="dialog" aria-modal="true" aria-label={note ? 'New note' : 'File upload'} onClick={e => e.stopPropagation()} onKeyDown={e => { trapFocus(e); if (e.key === 'Escape' && !busy) onClose(); }}><div className="modal-title"><div><div className="eyebrow">{project.name}</div><h2>{note ? 'New note' : 'Add materials'}</h2></div><button ref={closeRef} className="icon-button" aria-label="Close" disabled={busy} onClick={onClose}><X size={20}/></button></div><label>Destination folder<input disabled={busy} value={folder} onChange={e => setFolder(e.target.value)} list="project-folders" placeholder="Project root or a new folder"/><datalist id="project-folders">{[...new Set(project.files.filter(f => f.path.includes('/')).map(f => f.path.slice(0, f.path.lastIndexOf('/'))))].map(p => <option key={p} value={p}/>)}</datalist></label>{note ? <label>Note name<input disabled={busy} value={name} onChange={e => setName(e.target.value)} placeholder="My observations.md"/></label> : <><label className={`dropzone ${drag ? 'dragging' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); if (!busy) setFiles(prev => [...prev, ...Array.from(e.dataTransfer.files)]); }}><Upload size={27}/><strong>Drop your files here</strong><span>or click to browse</span><small>Documents, images, video and audio · up to 4 MB each</small><input type="file" multiple disabled={busy} onChange={e => setFiles(prev => [...prev, ...Array.from(e.target.files || [])])}/></label><div className="upload-files">{files.map((f, i) => <div key={`${f.name}-${i}`}><FileText size={15}/><span>{f.name}</span><small>{sizeOf(f.size)}</small><button className="icon-button" aria-label={`Remove ${f.name}`} disabled={busy} onClick={() => setFiles(prev => prev.filter((_, j) => i !== j))}><X size={14}/></button></div>)}</div></>}{error && <div className="error" role="alert">{error}</div>}{progress && <p className="upload-progress">{progress}</p>}<footer><button className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy || (note ? !name.trim() : !files.length)} onClick={submit}>{busy ? <LoaderCircle className="spin" size={15}/> : <Plus size={15}/>} {busy ? 'Saving…' : note ? 'Create note' : `Upload${files.length ? ` (${files.length})` : ''}`}</button></footer></div></div>;
}
