'use client';
import { isValidElement, useCallback, useEffect, useRef, useState } from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { ArrowUpRight, ArrowLeft, ArrowRight, BookOpen, Bookmark, Check, ChevronDown, ChevronRight, Code2, Copy, Download, FileText, Files, Folder, Grid2X2, Image as ImageIcon, LayoutGrid, List, LoaderCircle, LogOut, Maximize2, Menu, Plus, Search, ShieldCheck, Upload, X, Pencil, Save, Play, Music, ExternalLink } from 'lucide-react';
import { fileKind, fileUrl, type Catalog, type Project } from '@/lib/types';
import { MediaViewer, UploadDialog } from './dialogs';
import { relativeLink } from '@/lib/content';
const titles: Record<string, string> = { 'project-overview.md': 'Project overview', 'project overview.md': 'Project overview', 'x-flow.md': 'X · Project timeline', 'x-mentions-flow.md': 'X · Mentions & discussions', 'whyitsent.md': 'Why it took off', 'website-analysis.md': 'Website analysis', 'other-info.md': 'Additional research', 'project-info.json': 'Project information', 'research-data.json': 'Research data' };
const titleOf = (p: string) => titles[p.toLowerCase()] || p.split('/').pop() || p;
const statuses = { complete: 'Researched', research: 'In progress', template: 'Template', guide: 'Guide' };
const sizeOf = (n: number) => n < 1024 ? `${n} B` : n < 1024 ** 2 ? `${(n / 1024).toFixed(0)} KB` : `${(n / 1024 ** 2).toFixed(1)} MB`;
const initials = (name: string) => name.split(/[ .]+/).slice(0, 2).map(s => s[0]).join('').toUpperCase();
const colors = ['sage', 'sand', 'rose', 'blue', 'lavender', 'clay', 'sage'];
const safeHref = (s?: string) => s && /^https?:\/\//i.test(s) ? s : undefined;
const nodeText = (node: React.ReactNode): string => Array.isArray(node) ? node.map(nodeText).join('') : isValidElement<{ children?: React.ReactNode }>(node) ? nodeText(node.props.children) : String(node ?? '');
const headingId = (s: string) => s.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu, '').replace(/\s+/g, '-');
export async function api(url: string, init?: RequestInit) {
  const response = await fetch(url, init);
  if (response.status === 401) { location.href = '/login'; throw new Error('Your session has expired'); }
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || 'Could not complete the request'); }
  return response;
}
export default function Workspace() {
  const [data, setData] = useState<Catalog | null>(null); const [error, setError] = useState('');
  const [projectId, setProjectId] = useState(''); const [path, setPath] = useState(''); const [view, setView] = useState('library');
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [layout, setLayout] = useState('grid');
  const [favorites, setFavorites] = useState<string[]>([]); const [tab, setTab] = useState('documents');
  const [content, setContent] = useState(''); const [draft, setDraft] = useState(''); const [rev, setRev] = useState('');
  const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState(''); const [media, setMedia] = useState<string | null>(null);
  const [upload, setUpload] = useState(false); const [newNote, setNewNote] = useState(false);
  const [mobile, setMobile] = useState(false); const [wide, setWide] = useState(false); const [fileQuery, setFileQuery] = useState('');
  const searchRef = useRef<HTMLInputElement>(null);
  const activeUrl = useRef('/');
  const project = data?.projects.find(p => p.id === projectId); const selectedFile = project?.files.find(f => f.path === path);
  const dirty = editing && draft !== content; const dirtyRef = useRef(dirty); dirtyRef.current = dirty;
  const refresh = useCallback(async () => { const result = await api('/api/catalog'); setData(await result.json()); setError(''); }, []);
  useEffect(() => {
    refresh().catch(e => setError(e.message));
    try { setFavorites(JSON.parse(localStorage.getItem('kai-favorites') || '[]')); } catch { /* empty favorites */ }
    const restore = () => { if (dirtyRef.current && !confirm('You have unsaved changes. Leave without saving?')) { history.pushState({}, '', activeUrl.current); return; } activeUrl.current = location.pathname + location.search; const params = new URLSearchParams(location.search); setProjectId(params.get('project') || ''); setPath(params.get('file') || ''); setEditing(false); };
    restore(); window.addEventListener('popstate', restore);
    const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); searchRef.current?.focus(); } };
    window.addEventListener('keydown', key);
    const unload = (e: BeforeUnloadEvent) => { if (dirtyRef.current) e.preventDefault(); };
    window.addEventListener('beforeunload', unload);
    return () => { window.removeEventListener('popstate', restore); window.removeEventListener('keydown', key); window.removeEventListener('beforeunload', unload); };
  }, [refresh]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timer); }, [notice]);
  useEffect(() => { if (!project || path || !project.files.length) return; const preferred = project.files.find(f => f.path === 'X-Flow.md') || project.files.find(f => f.path === 'project-overview.md') || project.files[0]; setPath(preferred.path); }, [project, path]);
  useEffect(() => {
    if (!projectId || !path || fileKind(path) !== 'document') { setContent(''); setLoading(false); return; }
    const controller = new AbortController(); setLoading(true); setError(''); setContent(''); setDraft(''); setRev('');
    api(fileUrl(projectId, path), { signal: controller.signal }).then(async res => { const text = await res.text(); if (!controller.signal.aborted) { setContent(text); setDraft(text); setRev(res.headers.get('x-revision') || ''); } }).catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [projectId, path]);
  const canLeave = () => !dirty || confirm('You have unsaved changes. Leave without saving?');
  function navigate(id: string, nextPath = '', nextView = 'library') {
    if (!canLeave()) return; setProjectId(id); setPath(nextPath); setView(nextView); setEditing(false); setError(''); setQuery(''); setMobile(false); setFileQuery(''); setTab('documents');
    const params = new URLSearchParams(); if (id) params.set('project', id); if (nextPath) params.set('file', nextPath); activeUrl.current = params.size ? `/?${params}` : '/'; history.pushState({}, '', activeUrl.current);
  }
  function chooseFile(p: string) {
    if (['image', 'video', 'audio'].includes(fileKind(p))) { setMedia(p); return; }
    if (!canLeave()) return; setPath(p); setEditing(false); setError(''); setTab('documents'); activeUrl.current = `/?${new URLSearchParams({ project: projectId, file: p })}`; history.pushState({}, '', activeUrl.current);
  }
  function favorite(id: string) { const next = favorites.includes(id) ? favorites.filter(f => f !== id) : [...favorites, id]; setFavorites(next); localStorage.setItem('kai-favorites', JSON.stringify(next)); }
  async function save() {
    setSaving(true); setError('');
    try { const res = await api('/api/file', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: projectId, path, content: draft, revision: rev }) }); const result = await res.json(); setContent(draft); setRev(result.revision); setEditing(false); setNotice('Changes saved'); await refresh(); } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setNotice('Copied to clipboard'); } catch { setNotice('Could not copy to clipboard'); } }
  function localLink(href: string) {
    if (!project) return;
    try { const resolved = relativeLink(path, href);
      if (project.files.some(f => f.path === resolved)) chooseFile(resolved);
      else if (project.files.some(f => f.path.startsWith(resolved.replace(/\/$/, '') + '/'))) { if (!canLeave()) return; setFileQuery(resolved.replace(/\/$/, '')); setTab('media'); }
      else setNotice('The linked file was not found in this project');
    } catch { setNotice('Could not open the link'); }
  }
  const allProjects = data?.projects.filter(p => p.status !== 'guide') || [];
  const filtered = allProjects.filter(p => (view !== 'favorites' || favorites.includes(p.id)) && (filter === 'all' || p.status === filter) && `${p.name} ${p.ticker} ${p.files.map(f => f.path).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const imageCount = allProjects.reduce((n, p) => n + p.files.filter(f => f.kind === 'image').length, 0);
  const documentCount = allProjects.reduce((n, p) => n + p.files.filter(f => f.kind === 'document').length, 0);
  const mediaFiles = project?.files.filter(f => ['image', 'video', 'audio'].includes(f.kind)) || [];
  const toc = [...content.matchAll(/^#{1,3}\s+(.+)$/gm)].map(m => m[1]).slice(0, 35);
  const contract = project && Object.entries(project.info).find(([k]) => /^contract/i.test(k))?.[1];
  return <div className={`app-shell ${mobile ? 'mobile-open' : ''}`}>
    {mobile && <button className="sidebar-scrim" aria-label="Close menu" onClick={() => setMobile(false)}/>}
    <aside className="sidebar"><button className="brand" onClick={() => navigate('')}><span className="brand-mark">l<span>↗</span></span><span>research lounge<small>RESEARCH WORKSPACE</small></span></button><div className="workspace-label"><span className="workspace-avatar">R</span><div>Personal workspace<small>Private library</small></div><ShieldCheck size={15}/></div><div className="nav-label">WORKSPACE</div>
      <nav><button className={!projectId && view === 'library' ? 'active' : ''} onClick={() => navigate('')}><LayoutGrid size={17}/>All projects<span className="nav-count">{allProjects.length}</span></button><button className={!projectId && view === 'favorites' ? 'active' : ''} onClick={() => navigate('', '', 'favorites')}><Bookmark size={17}/>Favorites<span className="nav-count">{favorites.length}</span></button><button className={projectId === '_guide' ? 'active' : ''} onClick={() => navigate('_guide')}><BookOpen size={17}/>Research playbook</button></nav><div className="nav-label projects-nav-label">CASE STUDIES <span>{allProjects.length.toString().padStart(2, '0')}</span></div><nav className="project-nav">{allProjects.map((p, i) => <button key={p.id} className={projectId === p.id ? 'active' : ''} onClick={() => navigate(p.id)}><span className={`project-dot ${colors[i % colors.length]}`}/><span>{p.name}</span>{p.status === 'complete' && <Check size={12} className="project-check"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="private-note"><span className="online-dot"/><div>Your space to think<small>Connect ideas. See the bigger picture.</small></div></div><button className="user-menu" onClick={async () => { if (!canLeave()) return; await api('/api/auth', { method: 'DELETE' }); location.href = '/login'; }}><span className="user-avatar">A</span><span>Admin<small>Library owner</small></span><LogOut size={16}/></button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-toggle" aria-label="Open menu" onClick={() => setMobile(true)}><Menu size={20}/></button><span>Research Lounge</span><ChevronRight size={13}/><strong>{project?.name || (view === 'favorites' ? 'Favorites' : 'All projects')}</strong></div><div className="topbar-right"><span className="private-badge"><ShieldCheck size={13}/> Private library</span><span className="user-avatar small">A</span></div></header>
    {!data ? <div className="loading-state">{error ? <><p className="error">{error}</p><button className="secondary" onClick={() => refresh().catch(e => setError(e.message))}>Try again</button></> : <><LoaderCircle className="spin"/>Loading your library…</>}</div> : !project ? <main className="library-page">
      <div className="page-title"><div><div className="eyebrow">THE RESEARCH COLLECTION</div><h1>{view === 'favorites' ? 'Favorite projects' : 'Project library'}<span className="title-dot">.</span></h1><p>Collect details. Spot patterns. Discover ideas.</p></div><span className="collection-number">/ {allProjects.length.toString().padStart(2, '0')}</span></div>
      <div className="stats-row"><div><Folder size={18}/><strong>{allProjects.length.toString().padStart(2, '0')}</strong><span>case studies</span></div><div><FileText size={18}/><strong>{documentCount}</strong><span>documents</span></div><div><ImageIcon size={18}/><strong>{imageCount}</strong><span>media files</span></div><div className="stats-note"><span className="online-dot"/>Everything in one place</div></div>
      <div className="collection-toolbar"><div className="filter-tabs">{[['all', 'All projects'], ['complete', 'Researched'], ['research', 'In progress']].map(([id, label]) => <button key={id} className={filter === id ? 'selected' : ''} onClick={() => setFilter(id)}>{label}{id === 'all' && <span>{allProjects.length}</span>}</button>)}</div><div className="toolbar-actions"><div className="search-box"><Search size={16}/><input ref={searchRef} placeholder="Find a project or file…" aria-label="Find a project or file" value={query} onChange={e => setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="view-toggle"><button aria-label="Grid view" className={layout === 'grid' ? 'selected' : ''} onClick={() => setLayout('grid')}><Grid2X2 size={16}/></button><button aria-label="List view" className={layout === 'list' ? 'selected' : ''} onClick={() => setLayout('list')}><List size={17}/></button></div></div></div>
      <div className={`project-grid ${layout === 'list' ? 'list-layout' : ''}`}>{filtered.map(p => { const i = allProjects.indexOf(p); const docs = p.files.filter(f => f.kind === 'document').length; const media = p.files.filter(f => ['image','video','audio'].includes(f.kind)).length; return <article className={`project-card ${colors[i % colors.length]}`} key={p.id}><button className="card-cover" aria-label={`Open ${p.name}`} onClick={() => navigate(p.id)}><div className="cover-grid"/><span className="cover-index">CASE STUDY / {(i + 1).toString().padStart(2, '0')}</span><span className="cover-monogram">{initials(p.name)}</span><span className="cover-ticker">{p.ticker ? `$${p.ticker}` : p.status === 'template' ? 'YOUR NEXT IDEA' : 'RESEARCH IN PROGRESS'}</span><span className="cover-arrow"><ArrowUpRight size={20}/></span></button><div className="card-body"><div className="card-title-row"><button onClick={() => navigate(p.id)}><h2>{p.name}</h2></button><button className={`bookmark-button ${favorites.includes(p.id) ? 'bookmarked' : ''}`} aria-label={`Favorite: ${p.name}`} onClick={() => favorite(p.id)}><Bookmark size={17} fill={favorites.includes(p.id) ? 'currentColor' : 'none'}/></button></div><div className={`status ${p.status}`}><span/>{statuses[p.status]}</div><div className="card-metrics"><div><small>ALL-TIME HIGH</small><strong>{p.info.ATH || '—'}</strong></div><div><small>LIFETIME VOLUME</small><strong>{p.info['Lifetime Volume'] || '—'}</strong></div></div><div className="card-footer"><span><FileText size={13}/>{docs} documents</span><span><ImageIcon size={13}/>{media} media</span><button aria-label={`Go to ${p.name}`} onClick={() => navigate(p.id)}><ArrowRight size={17}/></button></div>{query && p.files.filter(f => f.path.toLowerCase().includes(query.toLowerCase())).slice(0, 3).map(f => <button key={f.path} className="search-file-result" onClick={() => { navigate(p.id, f.path); if (f.kind === 'image') setMedia(f.path); }}><FileText size={12}/>{f.path}</button>)}</div></article>; })}</div>
      {filtered.length === 0 && <div className="empty-state"><Search size={30}/><h3>Nothing here yet</h3><p>Try another search or add a project to your favorites.</p><button className="secondary" onClick={() => { setQuery(''); setFilter('all'); }}>Reset filters</button></div>}
      <div className="library-bottom"><span>Every launch tells a story. Keep what matters.</span><span>RESEARCH LOUNGE <ArrowUpRight size={14}/></span></div>
    </main> : <main className="project-page">
      <button className="back-link" onClick={() => navigate('')}><ArrowLeft size={15}/>All projects</button>
      <section className="project-header"><div className={`project-emblem ${colors[Math.max(0, allProjects.findIndex(p => p.id === project.id)) % colors.length]}`}>{initials(project.name)}</div><div className="project-heading"><div className="eyebrow">{project.status === 'guide' ? 'THE PLAYBOOK' : 'CASE STUDY'}<span className={`status ${project.status}`}><span/>{statuses[project.status]}</span></div><h1>{project.name}<span className="ticker">{project.ticker && `$${project.ticker}`}</span></h1><div className="project-links">{[['X', project.info.X], ['Website', project.info.Website], ['GMGN', project.info['gmgn link']]].map(([label, url]) => safeHref(url) && <a key={label} href={url} target="_blank" rel="noopener noreferrer">{label}<ArrowUpRight size={13}/></a>)}{contract && <button className="contract" onClick={() => copy(contract)}>{contract.slice(0, 7)}…{contract.slice(-5)}<Copy size={12}/></button>}</div></div><button className={`secondary favorite-detail ${favorites.includes(project.id) ? 'bookmarked' : ''}`} onClick={() => favorite(project.id)}><Bookmark size={15} fill={favorites.includes(project.id) ? 'currentColor' : 'none'}/>{favorites.includes(project.id) ? 'Favorited' : 'Add to favorites'}</button></section>
      <div className="project-stats"><div><small>ALL-TIME HIGH</small><strong>{project.info.ATH || '—'}</strong></div><div><small>LIFETIME VOLUME</small><strong>{project.info['Lifetime Volume'] || '—'}</strong></div><div><small>DOCUMENTS</small><strong>{project.files.filter(f => f.kind === 'document').length}<span>files</span></strong></div><div><small>MEDIA LIBRARY</small><strong>{mediaFiles.length}<span>files</span></strong></div></div>
      {!data.writable && <div className="storage-warning">Read-only mode. Connect a private Vercel Blob store to save changes.</div>}
      <div className="project-tabs"><div>{[['documents', 'Documents', FileText], ['media', 'Media library', ImageIcon], ['files', 'All files', Files]].map(([id, label, Icon]) => { const TabIcon = Icon as typeof FileText; return <button key={String(id)} className={tab === id ? 'selected' : ''} onClick={() => { if (canLeave()) { setTab(String(id)); setEditing(false); setFileQuery(''); } }}><TabIcon size={16}/>{String(label)}{id === 'media' && <span>{mediaFiles.length}</span>}</button>; })}</div><button className="secondary upload-trigger" disabled={!data.writable} onClick={() => setUpload(true)}><Upload size={15}/>Upload files</button></div>
      {error && <div className="error project-error" role="alert">{error}<button aria-label="Dismiss error" onClick={() => setError('')}><X size={14}/></button></div>}
      {tab === 'documents' ? <div className={`document-workspace ${wide ? 'wide-reading' : ''}`}><aside className="file-sidebar"><div className="file-sidebar-title">MATERIALS<button aria-label="New note" disabled={!data.writable} onClick={() => setNewNote(true)}><Plus size={16}/></button></div><div className="file-search"><Search size={13}/><input aria-label="Search files" placeholder="Find a file…" value={fileQuery} onChange={e => setFileQuery(e.target.value)}/></div>{[...new Set(project.files.filter(f => f.kind === 'document').map(f => f.path.includes('/') ? f.path.slice(0, f.path.lastIndexOf('/')) : ''))].map(folder => <div className="file-group" key={folder}><div className="file-group-label"><ChevronDown size={12}/><Folder size={13}/>{folder || 'Research'}</div>{project.files.filter(f => f.kind === 'document' && (f.path.includes('/') ? f.path.slice(0, f.path.lastIndexOf('/')) : '') === folder && `${f.path} ${titleOf(f.path)}`.toLowerCase().includes(fileQuery.toLowerCase())).map(f => <button className={`file-item ${path === f.path ? 'selected' : ''}`} key={f.path} onClick={() => chooseFile(f.path)}>{/\.json$/i.test(f.path) ? <Code2 size={15}/> : <FileText size={15}/>}<span>{titleOf(f.path)}</span></button>)}</div>)}<div className="file-sidebar-footer"><ShieldCheck size={13}/>Private materials</div></aside>
      <section className="reader"><div className="reader-toolbar"><div><FileText size={15}/><span title={path}>{path.split('/').pop() || 'Select a file'}</span>{dirty && <span className="unsaved-dot" title="Unsaved changes"/>}</div><div>{editing ? <><button className="secondary" onClick={() => { if (canLeave()) { setEditing(false); setDraft(content); } }}>Cancel</button><button className="primary" disabled={saving || !dirty} onClick={save}>{saving ? <LoaderCircle size={14} className="spin"/> : <Save size={14}/>}Save</button></> : <>{selectedFile?.kind === 'document' && <button className="secondary edit-button" disabled={loading || !rev || !data.writable} onClick={() => setEditing(true)}><Pencil size={14}/>Edit</button>}<a className="icon-button" title="Download file" href={`${fileUrl(project.id, path)}&download=1`}><Download size={15}/></a><button className="icon-button" title="Wide reading mode" onClick={() => setWide(!wide)}><Maximize2 size={15}/></button></>}</div></div>
      {loading ? <div className="loading-state"><LoaderCircle className="spin"/>Opening document…</div> : editing ? <div className="editor-wrap"><div className="editor-hint"><Code2 size={14}/> {path.endsWith('.json') ? 'JSON' : 'Markdown'}<span>{draft.length.toLocaleString('en-US')} characters</span></div><textarea aria-label="File editor" className="editor" value={draft} spellCheck={false} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if ((e.ctrlKey || e.metaKey) && e.key === 's') { e.preventDefault(); if (!saving) save(); } }}/></div> : selectedFile?.kind === 'document' ? <div className="reading-layout"><article className="prose"><div className="document-meta">{path.endsWith('.json') ? 'PROJECT DATA' : 'RESEARCH NOTE'}<span>~{Math.max(1, Math.ceil(content.split(/\s+/).length / 220))} min read</span></div>{!/^#\s/m.test(content) && <h1>{titleOf(path)}</h1>}{/\.json$/i.test(path) ? <pre><code>{(() => { try { return JSON.stringify(JSON.parse(content), null, 2); } catch { return content; } })()}</code></pre> : <Markdown remarkPlugins={[remarkGfm]} components={{ h1: ({ children }) => <h1 id={headingId(nodeText(children))}>{children}</h1>, h2: ({ children }) => <h2 id={headingId(nodeText(children))}>{children}</h2>, h3: ({ children }) => <h3 id={headingId(nodeText(children))}>{children}</h3>, table: ({ children }) => <div className="table-scroll"><table>{children}</table></div>, a: ({ href, children }) => { if (!href) return <span>{children}</span>; if (href.startsWith('#')) return <a href={href}>{children}</a>; if (/^https?:\/\//i.test(href)) return <a href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={11}/></a>; if (/^[a-z]+:/i.test(href)) return <span>{children}</span>; return <button className="inline-link" onClick={() => localLink(href)}>{children}</button>; }, img: ({ src, alt }) => { if (typeof src !== 'string' || /^https?:|^\/\//i.test(src)) return <span className="muted">[External image: {alt}]</span>; const resolved = relativeLink(path, src); return <img src={fileUrl(project.id, resolved)} alt={alt || resolved} loading="lazy" onClick={() => setMedia(resolved)}/>; } }}>{content || '*This document is empty. Add your observations.*'}</Markdown>}<div className="document-end"><span/>END OF NOTE<span/></div></article>{toc.length > 2 && <aside className="toc"><span>ON THIS PAGE</span>{toc.map((h, i) => <a key={i} href={`#${headingId(h)}`}>{h.replace(/\*|`/g, '')}</a>)}</aside>}</div> : selectedFile && ['image','video','audio'].includes(selectedFile.kind) ? <div className="empty-state"><ImageIcon size={35}/><h3>{titleOf(path)}</h3><button className="primary" onClick={() => setMedia(path)}>Open media</button></div> : <div className="empty-state"><Files size={35}/><h3>{path || 'Select a document'}</h3>{path && <a className="secondary" href={`${fileUrl(project.id, path)}&download=1`}>Download file <Download size={14}/></a>}</div>}</section></div>
      : tab === 'media' ? <section className="media-section"><div className="media-toolbar"><div><h2>Visual research <span>{mediaFiles.length}</span></h2><p>Screenshots, details and context for your research.</p></div><select aria-label="Media folder" value={fileQuery} onChange={e => setFileQuery(e.target.value)}><option value="">All folders</option>{[...new Set(mediaFiles.map(f => f.path.includes('/') ? f.path.slice(0, f.path.lastIndexOf('/')) : ''))].filter(Boolean).map(folder => <option key={folder} value={folder}>{folder}</option>)}</select></div><div className="media-grid">{mediaFiles.filter(f => !fileQuery || f.path.startsWith(fileQuery + '/')).map(f => <button className="media-tile" key={f.path} onClick={() => setMedia(f.path)}><div className="media-thumb">{f.kind === 'image' ? <img src={fileUrl(project.id, f.path)} alt={f.path} loading="lazy"/> : f.kind === 'video' ? <Play size={34}/> : <Music size={34}/>}<span className="media-zoom"><Maximize2 size={18}/></span></div><strong>{f.path.split('/').pop()}</strong><span>{f.path.split('/').slice(0, -1).join('/') || 'Project root'} · {sizeOf(f.size)}</span></button>)}</div>{!mediaFiles.length && <div className="empty-state"><ImageIcon size={35}/><h3>Your media belongs here</h3><p>Upload your first images or videos.</p></div>}</section> : <section className="all-files"><div className="media-toolbar"><h2>All files <span>{project.files.length}</span></h2><div className="search-box"><Search size={15}/><input aria-label="Search all files" value={fileQuery} onChange={e => setFileQuery(e.target.value)} placeholder="File name…"/></div></div><div className="file-list-head"><span>NAME</span><span>SIZE</span><span>MODIFIED</span><span/></div>{project.files.filter(f => f.path.toLowerCase().includes(fileQuery.toLowerCase())).map(f => <div className="file-list-row" key={f.path}><button onClick={() => chooseFile(f.path)}>{f.kind === 'image' ? <ImageIcon size={17}/> : <FileText size={17}/>}<span>{f.path}</span></button><span>{sizeOf(f.size)}</span><span>{new Date(f.modified).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span><a className="icon-button" aria-label={`Download ${f.path}`} href={`${fileUrl(project.id, f.path)}&download=1`}><Download size={15}/></a></div>)}</section>}
    </main>}
    </div>
    {notice && <div className="toast" role="status"><Check size={17}/>{notice}</div>}
    {media && project && <MediaViewer project={project} files={mediaFiles} current={media} onChange={setMedia} onClose={() => setMedia(null)}/>}
    {(upload || newNote) && project && <UploadDialog project={project} note={newNote} onClose={() => { setUpload(false); setNewNote(false); }} onDone={async (p) => { await refresh(); setNotice(newNote ? 'Note created' : 'Files uploaded'); if (newNote && p) chooseFile(p); }}/ >}
  </div>;
}
